import org.junit.Test;

import com.dylan.rss_agg.Application;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'dylan' at '23/02/18 21:50' with Gradle 2.13
 *
 * @author dylan, @date 23/02/18 21:50
 */
public class ApplicationTest {
    @Test public void testSomeApplicationMethod() {
        Application classUnderTest = new Application();
    }
}
